IMAGE_NAME = "generic/debian9"
N = 2

# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 3
    end
    config.vm.boot_timeout = 6000

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", ip: "10.121.2.207", bridge: "enp2s0"
# "enp3s0"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "10.121.2.207",
                ansible_python_interpreter: "/usr/bin/python2"
            }
        end
        master.vm.boot_timeout = 6000
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "public_network", ip: "10.121.2.#{i + 207}", bridge: "enp2s0"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "10.121.2.#{i + 207}",
                    ansible_python_interpreter: "/usr/bin/python2"
                }
            end
            node.vm.boot_timeout = 6000
        end
    end

end