# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
    config.vm.box = "mrlesmithjr/linuxmint19-desktop"
    config.vm.hostname = "mint19"
    config.vm.box_check_update = false
    #config.vm.network "public_network", ip: "10.121.2.200"
    #config.disksize.size = '15GB'
    config.vm.boot_timeout = 600
    config.vm.provision "shell",
        path: "install.sh",
        args: "5.9.3"
    config.vm.provider "virtualbox" do |v|
        v.name = "mint19"
        v.memory = 2048
        v.cpus = 2
    end
end