# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.hostname = "debian201"
  config.vm.box_check_update = false
  config.vm.network "public_network", ip: "10.121.2.200"
  #config.vm.provision "shell", path: "install.sh"
  config.vm.provider "virtualbox" do |v|
    v.name = "debian9"
    v.memory = 1024
    v.cpus = 2
  end
  config.push.define "local-exec" do |push|
    push.inline = <<-SCRIPT
      sudo unlink /etc/localtime

      sudo ln -s /usr/share/zoneinfo/America/Fortaleza /etc/localtime

      printf "\n\rINICIANDO SCRIPT DE INSTALAÇÃO PARA DESENVOLVEDORES DA IT HAPPENS - GRUPO MATEUS ... \n\r"


      if ! sudo apt-get install htop -y
      then
          printf "Não foi possível instalar o terminal htop\n\r"
          exit 1
      fi
      printf "Instalação do git htop...\n\r"

      printf "\n\rSCRIPT FINALIZADO ... \n\r"
    SCRIPT
  end
end