# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.hostname = "debian201"
  config.vm.box_check_update = false
  config.vm.network "public_network", ip: "10.121.2.200"
  #config.vm.provision "shell", path: "install.sh"
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |v|
    v.name = "debian9"
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "shell" do |s|
    s.inline = "echo $1"
    s.inline = "sudo apt-get install htop -y"
    s.args   = "'hello, world!'"
  end
end